### ISSUE TITLE
Build not working with Packer 0.7.2, Go 1.4.1

### ISSUE THREAD

**Issue by booi** [xenserver/packer-builder-xenserver#33]
I successfully built a development version of packer in $GOPATH, however building packer-builder-xenserver in $GOPATH seems to not work. 

```
[15:26:22 booi@bear:packer-builder-xenserver 127]$ ./build.sh 
==> Getting dependencies...
# github.com/rdobson/packer-builder-xenserver/builder/xenserver/common
builder/xenserver/common/common_config.go:57: undefined: packer.ConfigTemplate
builder/xenserver/common/step_type_boot_command.go:27: undefined: packer.ConfigTemplate
==> Removing old directory...
Number of parallel builds: 8

-->    darwin/amd64: github.com/rdobson/packer-builder-xenserver/plugin/builder-xenserver-iso
-->    darwin/amd64: github.com/rdobson/packer-builder-xenserver/plugin/builder-xenserver-xva

2 errors occurred:
--> darwin/amd64 error: exit status 2
Stderr: # github.com/rdobson/packer-builder-xenserver/builder/xenserver/common
builder/xenserver/common/common_config.go:57: undefined: packer.ConfigTemplate
builder/xenserver/common/step_type_boot_command.go:27: undefined: packer.ConfigTemplate

--> darwin/amd64 error: exit status 2
Stderr: # github.com/rdobson/packer-builder-xenserver/builder/xenserver/common
builder/xenserver/common/common_config.go:57: undefined: packer.ConfigTemplate
builder/xenserver/common/step_type_boot_command.go:27: undefined: packer.ConfigTemplate
```

**Comment by rdobson** [comment]
Hi @booi ,

Thanks for pointing this out - it seems that the core packer code has diverged somewhat, hence if you're using the latest packer source the compilation no longer works.

I've raised the following PR to update the plugin to work with the new core code:
https://github.com/rdobson/packer-builder-xenserver/pull/35

As far as I can tell, the go version used shouldn't make a difference.

Thanks.

**Comment by empath** [comment]
I tried checking out the pull request, but the build process seems to download from the main branch instead of using the code in the local directory.  Any chance this is getting merged any time soon?
